"""Glasgow Airport (GLA) destinations — May 2026."""

DESTINATIONS = {
    "GLA": {
        "name": "Glasgow",
        "routes": {
            "ACE": "Lanzarote",
            "ADB": "Izmir",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BEB": "Benbecula",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGY": "Milan Bergamo",
            "BHD": "Belfast City",
            "BHX": "Birmingham",
            "BJV": "Bodrum",
            "BOJ": "Bourgas",
            "BRR": "Barra",
            "BRS": "Bristol",
            "BRU": "Brussels",
            "BUD": "Budapest",
            "CAL": "Campbeltown",
            "CDG": "Paris CDG",
            "CFN": "Donegal",
            "CFU": "Corfu",
            "CMF": "Chambery",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "EAS": "San Sebastian",
            "EFL": "Kefalonia",
            "FAO": "Faro",
            "FCO": "Rome",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HAJ": "Hanover",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "ILY": "Islay",
            "JER": "Jersey",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KOI": "Kirkwall",
            "KRK": "Krakow",
            "KTT": "Kittila",
            "LCA": "Larnaca",
            "LCY": "London City",
            "LDY": "Derry",
            "LGW": "London Gatwick",
            "LHR": "London Heathrow",
            "LIS": "Lisbon",
            "LPA": "Gran Canaria",
            "LSI": "Sumburgh",
            "LTN": "London Luton",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NQY": "Newquay",
            "OPO": "Porto",
            "ORK": "Cork",
            "PFO": "Paphos",
            "PMI": "Palma",
            "PRG": "Prague",
            "PSA": "Pisa",
            "PUY": "Pula",
            "RAK": "Marrakech",
            "REU": "Reus",
            "RHO": "Rhodes",
            "SOU": "Southampton",
            "SPU": "Split",
            "STN": "London Stansted",
            "SYY": "Stornoway",
            "SZG": "Salzburg",
            "TFS": "Tenerife South",
            "TRE": "Tiree",
            "TRN": "Turin",
            "VIE": "Vienna",
            "VRN": "Verona",
            "WRO": "Wroclaw",
            "ZRH": "Zurich",
            "ZTH": "Zante",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
